### ISSUE TITLE
Various Questions

### ISSUE THREAD

**Issue by neurofractal** [OHBA-analysis/MEG-ROI-nets#2]
Hey, 
I'm attempting to adapt this approach for some resting state data acquired on Elekta Neuromag and Yokogawa systems, data analysed in Fieldtrip followed by the MEG-ROI-nets code. Thank you very much for making the code available and with such detailed comments, which has allowed me to unpack some of the functions and use them without having data in SPM format! I'm getting sensible looking results in the alpha-band using the AAL atlas (Z>3.4).

![Imgur](https://i.imgur.com/QQvzUCI.png)

I have a few questions though:

1. How many iterations would you advise to generate the null matrices. I'm currently using 100... anymore than that creates issues with memory..

2. Would you advise using the symmetric or closest orthoganisaltion? What's the major difference between the two - they give pretty similar results?

3. I can't seem to get the 38(39?) region parcellation to work for me. Using ft_read_atlas('...giles_39_binary.nii.gz') gives me the following error:

Attempt to grow array along ambiguous dimension.

Error in ft_read_atlas (line 692)
      new_brick0(brick0==value(i)) = i;

Would you have another file with the regions more simply defined in MNI space?

4. When downsampling the amplitude envelope what advantage does taking the log transform have (makes data more normally distributed?)?

Cheers, 

Robert Seymour (Aston Brain Centre, Macquarie Department of Cognitive Science)

**Comment by GilesColclough** [comment]
Hi, Robert, 

Thanks for getting in touch. 

I don’t know who’s on this mailing list, but the current OHBA team may be better placed to respond - I’ve copied in Romesh and Mark explicitly. 

See my responses below - don’t hesitate to write back to clarify

Giles

> I have a few questions though:
> How many iterations would you advise to generate the null matrices. I'm currently using 100... anymore than that creates issues with memory..
> 

I think you don’t need many as it scrambles data from all the channels - but I’d have to check in my code what I used as default. 

One way to check quickly is that the correlation distribution in the null matrices looks nearly normal. May not need many to get to this point.
> 
> Would you advise using the symmetric or closest orthoganisaltion? What's the major difference between the two - they give pretty similar results?
> 
Closest. 
The symmetric approach normalises the power in each ROI, meaning that the magnitude information is less used. 
You’re right, if you’re using correlation matrices it doesn’t make much difference 
> 
> I can't seem to get the 38(39?) region parcellation to work for me. Using ft_read_atlas('...giles_39_binary.nii.gz') gives me the following error:
> 
Oh. I always read it in using OSL’s nii_quickread function. The team may be able to help with this one. 
> 
> Attempt to grow array along ambiguous dimension.
> 
> Error in ft_read_atlas (line 692)
> new_brick0(brick0==value(i)) = i;
> 
> Would you have another file with the regions more simply defined in MNI space?
> 
> When downsampling the amplitude envelope what advantage does taking the log transform have (makes data more normally distributed?)?

It does make it more normal. In general, as a power envelope is strictly positive, you’d expect natural fluctuations to be in proportion rather than difference (I.e the natural mode of variation is 10% increase rather than 10 unit increase). It makes sense therefore to model the joint distribution of envelopes as log normal rather than normal.

**Comment by neurofractal** [comment]
Hi @GilesColclough (perhaps @RomeshA or @woolrich could also advise...)

I am attempting to perform some source analysis/parcellation/connectivity using the 39 region atlas as specified in "How reliable are MEG resting-state connectivity metrics? G.L.Colclough et al.,". 

I read in the data using fieldtrip's ft_read_mri function

atlas = ft_read_mri('...osl/parcellations/giles_39_binary.nii.gz');

atlas.antomy is a (:,:,:,39) matrix in which the last dimension corresponds to different parcels (I assume?).

My question is what is the order of these regions in the atlas (1-39)? Plotting the location of the parcels does not seem to match Table 2 in "How reliable are MEG resting-state connectivity metrics? G.L.Colclough et al.,"... Could you clarify?

Cheers, 

Robert

**Comment by GilesColclough** [comment]
Hi, Robert, 

please see the attached file. 
You should be able to run it, and the variable NEW_ORDER should re-organise the parcellation into what we used in the publications. 
The labels in LABELS(NEW_ORDER) should also match.

Let us know if this doesn’t work

Thanks
Giles

**Comment by neurofractal** [comment]
Hi @GilesColclough thanks but I can't seem to find the attachment in the comment...

My email address can be found here if easier to attach via email... [https://www.ccd.edu.au/people/profile.php?memberID=1599](https://www.ccd.edu.au/people/profile.php?memberID=1599)

**Comment by delshadv** [comment]
Hi, 
I was wondering if anyone can help me on these three error or problems that I faced with ROInet group analysis:
1. By setting "Settings.nParallelWorkers=20" I get this error :  'nParallelWorkers' is not a recognized parameter.
2. Just by running OSL example for group ROInet and OSL sample data set, I face with below error:
Error using hilbert
Too many input arguments.
Error in ROInets.envelope_data/hilbert_envelope (line 131)
    HE(iVox,:) = abs(transpose(hilbert(transpose(signal(iVox,:)), nfft)));
Error in ROInets.envelope_data (line 65)
HE = hilbert_envelope(verbose);
Error in ROInets.run_individual_network_analysis (line 423)
        [nodeEnv, time_ds] = ROInets.envelope_data(nodeData,        ...
Error in ROInets.run_network_analysis (line 361)
        mats{iSession} = ROInets.run_individual_network_analysis(D,                          ...

3. Has OSL got AAL 90 Atlas for parcellation?

Thanks

**Comment by GilesColclough** [comment]
Hi! 
Thanks for your interest.
It’s been a while since I was involved, so others may have to help with the details

1. Something about attempts to parallelise the code is not working- I’ll need help from the OHBA team here

2. There is a namespace clash between field trip and base matlab stats package I think. I forget which is needed. Try ‘which hilbert’ as a way to diagnose

3. We think that using more ROIs than degrees of freedom in your sensors doesn’t make for very sensible or interpretable results. For this reason, we steered away from using the AAL atlas.

Best
Giles

**Comment by delshadv** [comment]
@GilesColclough Thanks Giles for your quick reply and help on diagnosing the problem.
 1. I was wondering if you could send me the ways ( like emails) for contacting OHBA team, because the emails that are mentioned in the codes has been failed to delivery. I have a lot of subjects and it would be really time taking without paralleling.
2. We should lay away filedtrip hilbert function. It works now. Thank you!
3. I have an AAL nii file but it is a 3D (:,:,:) Matlab matrix not 4D that OSL uses for parcellation. Do you have any solution?

Bests,
Delshad

**Comment by GilesColclough** [comment]
I’d get hold of Mark Woolrich directly, or try Andrew Quinn (not sure if he’s still there)

On point 3, I can’t recall the difference of encoding between files. I’d start with a nifti file for your parcellation that’s 4d, then read it into matlab with one of the osl read nifti functions

G

**Comment by woolrich** [comment]
Huge thanks Giles (hope you are well!)

@ Delshad, I am copying in Jonathan Hadida, who helps to support the ROInets code now.
Best, Mark.

On 10 Jul 2019, at 15:35, Giles Colclough <notifications@github.com<mailto:notifications@github.com>> wrote:

I’d get hold of Mark Woolrich directly, or try Andrew Quinn (not sure if he’s still there)

On point 3, I can’t recall the difference of encoding between files. I’d start with a nifti file for your parcellation that’s 4d, then read it into matlab with one of the osl read nifti functions

G

**Comment by jhadida** [comment]
@delshadv 

Hi delshadv,

Sorry for the delayed reply, and thanks for your interest in this toolbox. Please find replies to your questions below:

1. The best thing to do if you have questions in the future is to [open a new issue](https://github.com/OHBA-analysis/MEG-ROI-nets/issues) on GitHub. We try to be as responsive as possible, and this is also a good way to let others benefit from your questions, and from our answers. Please open a new issue for each new question, instead of posting in an existing thread as you did. I will be closing this thread after posting; feel free to start a _new_ issue if you have any more questions.

2. [Function shadowing](https://uk.mathworks.com/matlabcentral/answers/90268-shadowing-built-in-functions) is a very common issue with Matlab. In an ideal world, this could be solved if Matlab introduced namespace aliasing into the language (eg as in Python `import very_long_package as foo`, but I don't think this will happen any time soon... The next best thing is to use [package folders](https://uk.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html) (starting with a `+`), but unfortunately most software packages still distribute as "folders of scripts", which is bound to create issues like the one you had.

3. I assume that your volume contains integer labels for each region in the AAL atlas? In case you did not know this, the atlas is also available within the OSL package, simply type:
```
AAL = nii.load(fullfile( osldir, 'parcellations', 'ft_AAL.nii.gz' ));
```

However, as you may notice, this volume is sampled in MNI 2mm space. This spatial resolution is unreasonably high for a typical MEG source-reconstruction; we usually work in 8mm or 6mm MNI space. There are essentially two ways forwards:
 - Computing the source-reconstruction in 2mm space, and parcellating there.
 - Resampling the AAL atlas at a more coarse resolution matching your source-reconstructed data.

I would not advise the first possibility, as this would be highly inefficient. The second approach is not ideal either (resampling an atlas can lead to the loss of labels), but here is how you would do this:

```matlab
% load MNI mask at desired resolution (use 6mm if needed)
mask = nii.load(fullfile( osldir, 'std_masks', 'MNI152_T1_8mm_brain.nii.gz' ));
mask = logical(mask);

% resample the AAL mask
AAL_sub = imresize3( AAL, size(mask), 'nearest' );

% make sure we didn't lose any label
assert( numel(unique(AAL_sub)) == numel(unique(AAL)), 'Labels were lost during resampling :(' );

% extract atlas voxels within the brain mask
atlas = AAL_sub(mask);

% convert label volume to logical ROIs
label = nonzeros(unique(atlas));
nvox = nnz(mask);
nroi = numel(label);
rois = false(nvox, nroi);

for i = 1:nroi
    rois(:,i) = atlas == label(i);
end
```

Looking at `sum(rois)` gives you the number of voxels in each region; as you can see, at this resolution, there are some regions with only one voxel in them! This is one reason why we try to steer away from the AAL atlas in MEG, as Giles mentioned. As an alternative, you may consider the Desikan-Kiliany atlas instead, or Giles' own functional parcellation with 39 ROIs. 

As I said I am closing this issue now, as your posts are unrelated to the OP; but please feel free to open a new issue if needed.
