### ISSUE TITLE
 run_network_analysis: Parallelizing Error

### ISSUE THREAD

**Issue by delshadv** [OHBA-analysis/MEG-ROI-nets#4]
According to OSL wiki and run_network_analysis code, we can define nParallelWorkers to analyse several sessions in parallel, but it seems it has not define yet and does not work! If one define nParallelWorkers it causes error.

Best Regards,
Delshad

**Comment by jhadida** [comment]
@delshadv It looks like the parallel option was added to the helptext prior to being implemented; I cannot find any use of it in the toolbox, or any attempt at parallelising the computations.

So unfortunately, this means that there is currently no built-in parallelisation for the analysis, and I am marking this issue as a possible future enhancement. Apologies for this :confused:

That being said however, I suppose what you would like to parallelise is the computation of individual network analyses in your cohort, is that correct? If so, it would be straightforward to parallelise the calls to `run_individual_network_analysis` manually.

At this stage, it is important for me to know:

 1. What type of dataset are you analysing? Is this resting-state or task data (i.e. do you want to run a GLM analysis or not)?
 2. What sort of parallelisation did you have in mind? For example using [`parfor`](https://uk.mathworks.com/help/matlab/ref/parfor.html), or [`spmd`](https://uk.mathworks.com/help/parallel-computing/spmd.html), or manually on a computing cluster (OGE, SGE, SLURM, etc), or something else?

**Comment by delshadv** [comment]
Thanks @jhadida, 
Yes it's correct, because if you have more than 100 subjects (that I have) running run_network_analysis takes time more than one week!!!. So analyse several subjects in parallel on a linux cluster would be a good solution:
1. I am analyzing concatenated resting state data.
2. Yes, using parfor for example on a Linux cluster network.

Bests,

**Comment by jhadida** [comment]
@delshadv 

With resting state data, it is just the case of:

 - parallelising calls to `run_individual_network_analysis`, saving the output correlation matrices for each subject independently;
 - gathering all the correlation matrices into a cell-array (call it `gatheredResults`), and calling `ROInet.reformat_results( gatheredResults, Settings )`;
 - saving the reformatted results for further analysis.

The group analysis can then be run as in [these lines](https://github.com/OHBA-analysis/MEG-ROI-nets/blob/3dbd03da2604bd39d9a3dc728ecc96acee452750/%2BROInets/run_network_analysis.m#L382-L394).

If you already have a Linux cluster available with Matlab parallel toolbox setup, this should be pretty straightforward. Let me know if you need further help, otherwise can I close this issue?

**Comment by delshadv** [comment]
Yes, Thanks.
